apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep
  annotations:
    lxcfs-webhook.paradeum.com/mutate: "false"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sleep
  template:
    metadata:
      labels:
        app: sleep
    spec:
      serviceAccountName: lxcfs-webhook-sa
      containers:
      - name: sleep
        image: tutum/curl
        command: ["/bin/sleep","infinity"]
        imagePullPolicy: IfNotPresent